[default]
model = "gpt-4o-2024-11-20"
desired_coverage = 90
max_iterations = 10
api_base = "http://localhost:11434"
max_run_time_sec = 30
run_tests_multiple_times = 1
log_db_path = "cover_agent_unit_test_runs.db"
branch = "main"
diff_coverage = false
included_files = []
coverage_type = "cobertura"
report_filepath = "test_results.html"
run-each-test-separately = false

# TODO: Uncomment the following lines after merging PRs #323 and #324
#responses_folder = "stored_responses"

#cover_agent_host_folder = "dist/cover-agent"
#cover_agent_container_folder = "/usr/local/bin/cover-agent"

#docker_hash_display_length = 12
#record_replay_hash_display_length = 12

#fuzzy_lookup_threshold = 95
#fuzzy_lookup_prefix_length = 1000
#fuzzy_lookup_best_ratio = 0

[include_files]
limit_tokens = true
max_tokens = 20000

[tests]
max_allowed_runtime_seconds = 30
